title: AVERtek # your name photo (or website title) here
logo: "/images/New XR-ASAP logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  View 3D image; scale, rotate, spin
  <br><br>
  View in Augmented Reality; press AR button lower screen, place image in real space, scale and view 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
